# Generated by Django 4.1.5 on 2023-01-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
