# Generated by Django 4.1.5 on 2023-01-19 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choices_vote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
    ]
